Sprint2/step2...
Druss25/react-burger pull request #4
Opened 2022-10-18 11:13 UTC by Druss25

2022-10-30 09:30 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **очень хорошую** работу, **корректно** подключили и использовали Redux и DnD в ваше проекте, добавили **удобные** заглушки в конструктор ингредиентов, **применили** часть возможностей тулкита через библиотеку `reselect`, **удобно** организовали структуру вашего проекта, написали **лаконичный** и понятный код, так держать 👍 

Однако, для успешной сдачи работы, вам необходимо изучить и **исправить**, указанные в рамках ревью моменты, включая следующие:

- В модальном окне с подробностями ингредиента числовые значения дублируются (https://disk.yandex.ru/i/2BIsrpkTDFVALA)
- В связи с тем, что вы выбрали использование TS в рамках описания Редакса, следует прописать правильную типизацию в файле. Использование any позволяет передать абсолютно любое значение в функцию, что может привести к ошибкам, в случае если ожидаемый объект будет отличаться от переданного. 

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

Отдельно отмечу, что инициатива студентов, безусловно, поощряется, и у вас круто получается, однако **на типизацию** выделены отдельные спринты и имеет смысл делать всё поэтапно, не забегая вперёд, чтобы в будущем не было необходимости переписывать какие-то моменты :)

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга, хорошего настроения и отличных выходных!** 🐈 

_P.S. **Не следует** производить отправку изменений в ваш PR после передачи его на ревью._

2022-10-30 09:30 UTC, randomroot commented on src/components/App/App.jsx
> +    <IngredientContext.Provider value={{ ingredients, setIngredients }}>
🔴 **Нужно исправить:**

В рамках данного этапа используется Redux хранилище, поэтому следует отказаться от использования контекстов из предыдущего этапа;

2022-10-30 09:30 UTC, randomroot commented on src/services/store/index.ts
> +// export const store = configureStore({
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-10-30 09:30 UTC, randomroot commented on src/services/reducers/order/actions.ts
> +export const getOrder = (requestData: any) => {
🔴 **Нужно исправить:**

В связи с тем, что вы выбрали использование TS, следует прописать правильную типизацию в файле. Использование `any` позволяет передать абсолютно любое значение в функцию, что может привести к ошибкам, в случае если ожидаемый объект будет отличаться от переданного.

Также отмечу, что на типизацию выделены отдельные спринты и имеет смысл делать всё поэтапно, не забегая вперёд, чтобы в будущем не было необходимости переписывать какие-то моменты :)

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    console.log(numberOrder)
🟡 **Можно улучшить:**

Следует убрать логгирование, используемое на этапе разработки и отладки

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                style={{ width: '100%', textAlign: 'center' }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

Здесь и далее в рамках файла

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div
🟢 **Отлично:**

Интересное решение по отображению заглушек в бургере 👍

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructorElement/BurgerConstructorElement.jsx
> +    accept: ["SORTING_INGREDIENT"],
🟡 **Можно улучшить:**

Данное значение имеет смысл выделить в отдельную константу, чтобы переиспользовать её в нескольких местах и изменять при необходимости только в одном

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructorElement/BurgerConstructorElement.jsx
> +      console.log(item.index)
🟡 **Можно улучшить:**

Следует убрать логгирование, используемое на этапе разработки и отладки

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [currentTab, setCurrentTab] = React.useState("bun");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const titleModal = "Детали ингредиента";
🟡 **Можно улучшить:**

Данное значение имеет смысл вынести за пределы компоненты, чтобы не пересоздавать его заново при каждом рендере :)

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [bunsRef, inBunsView] = useInView({ threshold: 0 })
🟢 **Отлично:**

Прекрасный выбор вспомогательной библиотеки 👍

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const selectTab = document.getElementById(value);
🟡 **Можно улучшить:**

В данном случае целесообразно использовать заготовленные рефы и обращаться к элементам через них, т.к. нативные операции выбиваются из подхода React-а

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const buns = React.useMemo(
🟡 **Можно улучшить:**

В рамках файла `src/services/reducers/ingredients/selectors.ts` вы указали селекторы с той же логикой, что обозначена в данном файле, имеет смысл переиспользовать их, чтобы убрать дублирование кода.

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [isIngredientModal, setIsIngredientModal] = React.useState({});
🟡 **Можно улучшить:**

1) Название переменной `isIngredientModal` наводит на мысль, что это `boolean` значение, но на самом деле это объект. Поэтому, имеет смысл переименовать её в более подходящий вариант, например `selectedIngredient`
2) Начальное значение, которое считается пустым, лучше задавать через `null` или `undefined`, чтобы избежать возможных проблем в дальнейшим обращением к пустому объекту в котором нет ключей (возможно неправильное поведение UI, сложнее отслеживать корректность кода в отсутствии проверок)

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerIngredientsCategory/BurgerIngredientsCategory.jsx
> +// BurgerIngredientsCategory.propTypes = {
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-10-30 09:30 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.jsx
> +          <p className='text text_type_main-medium text-center mt-2'>{currentIngredient.calories}</p>
🔴 **Нужно исправить:**

Дублируются значения "калорий" во всех элементах таблицы

2022-10-30 09:30 UTC, randomroot commented on src/index.tsx
> -  <React.StrictMode>
🟡 **Можно улучшить:**

Не следует отключать `React.StrictMode` из проекта, т.к. он помогает отслеживать возможные побочные эффекты про реализации ваших хуков и использовании встроенных, плюс напоминает о проблемах совместимости со старыми версиями Реакта. Поэтому, если возникают сложности только при его наличии, то в первую очередь лучше еще раз перепроверить код, а потом при крайне необходимости отключить "строгий режим"

2022-10-30 09:30 UTC, randomroot commented on src/components/IngredientElement/IngredientElement.jsx
> +          <img src={image} alt='img_ingredient' />
🟡 **Можно улучшить:**

Значение `alt` следует сделать человекочитаемым, т.к. оно используется чтобы вывести на экран информацию о том, что находится на данном изображении, когда оно не было загружено, а также для людей с ограниченными возможностями, которым текущий вариант возможно будет непонятен. Это правило распространяется для любого `img` за исключением декоративных, где атрибут можно не указывать

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructorElement/BurgerConstructorElement.jsx
> +            payload: index
🟡 **Можно улучшить:**

В качестве значения, для определения удаляемого элемента, можно использовать также его `id`, чтобы в редьюсере провести операцию за одно действие с помощью функции `.filter`, создав всего 1 массив, без использования 2-ух промежуточных через `slice` :)

2022-10-30 09:30 UTC, randomroot commented on package.json
> +    "reselect": "^4.1.6",
🟡 **Можно улучшить:**

Обратите внимание, что функционал данной библиотеки входит в комплект `@reduxjs/toolkit`:
`import { createSelector } from '@reduxjs/toolkit'`

Поэтому имеет смысл оставить только что-то одно, и, возможно, отказаться в первую очередь от тулкита, т.к. вы не используете его в рамках проекта.

2022-10-30 09:30 UTC, randomroot commented on src/services/reducers/ingredients/actions.ts
> +    const res = await fetch(`${baseUrl}/ingredients`);
🟡 **Можно улучшить:**

Работу с API и проверку результата имеет смысл вынести в отдельный файл с утилитами, чтобы исключить дублирование кода

2022-10-30 09:30 UTC, randomroot commented on src/services/reducers/ingredient-modal/actions.ts
> +export const name = "modal";
🟡 **Можно улучшить:**

Данной переменной лучше задать более уточняющие название, т.к. `name` - слишком общее и не совсем понятно, что оно определяет

2022-10-30 09:30 UTC, randomroot commented on src/services/reducers/burger/selectors.ts
> +      ingredients.reduce((total: any, value: any) => total + value.price, 0)
🔴 **Нужно исправить:**

Типизация параметров функции `reduce` может быть определена однозначно как `number`, следует отказаться от использования `any`.

2022-10-30 09:30 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const isOpenModalWindow = () => {
🟡 **Можно улучшить:**

Обычно, с приставкой `is` обозначаются переменные, которые означают логические значения, функции целесообразнее называть согласно действию, например `openModalWindow`

2022-10-30 15:50 UTC, randomroot requested changes
Вы **успешно** исправили большую часть замечаний, **однако** остались еще пара небольших моментов, которые потребуют вашего внимания и исправлений, связанные с именованиями функций и типизацией, отмеченные в рамках текущей итерации ревью.

После их корректировки работа будет принята. **Успехов!**

2022-10-30 15:50 UTC, randomroot commented on src/components/IngredientElement/IngredientElement.jsx
> +          <img src={image} alt='Инградиент' />
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2022-10-30 15:50 UTC, randomroot commented on src/services/reducers/order/actions.ts
> +export const getOrder = (requestData: []) => {
🔴 **Нужно исправить:**

`[]` не описывает конкретную типизацию параметра `requestData`, следует полностью описать ожидаемый тип. В данном случае это будет массив строк - `string[]`

2022-10-30 15:50 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const OpenModalWindow = () => {
🔴 **Нужно исправить:**

Название функции следует привести к формату `camelCase`

2022-10-30 17:29 UTC, Druss25 commented on src/index.tsx
> -  <React.StrictMode>
Это замечание я исправил

2022-10-30 17:30 UTC, Druss25 commented on package.json
> +    "reselect": "^4.1.6",
@reduxjs/toolkit удалил

2022-10-31 07:45 UTC, randomroot approved these changes
🟢 **Работа принята**

Необходимые изменения были успешно внесены, ожидаемый функционал работает полностью, хорошая работа 👍 

**Желаю вам успехов в дальнейшем обучении и отличного настроения!**

2022-10-31 08:27 UTC, merged